/**
 * Curated brand catalog for BrandIcon: slug → display title, every slug
 * verified against simple-icons 16.5.0 (the template's pinned major). The
 * brands.test.ts suite re-verifies the whole map against the *installed*
 * package on every run, so a simple-icons bump that drops a brand fails loudly
 * instead of silently rendering nothing.
 *
 * Known ABSENT from simple-icons v16 (removed upstream, usually brand-policy
 * takedowns) — do not add these; pick a stand-in or ship a local asset:
 * slack, salesforce, twitter (use `x`), openai, microsoft, amazon, linkedin,
 * adobe, canva, walmart, oracle, skype, microsoftteams, plaid.
 */
export const brands = {
  "1password": "1Password",
  airbnb: "Airbnb",
  airtable: "Airtable",
  americanexpress: "American Express",
  anthropic: "Anthropic",
  apple: "Apple",
  asana: "Asana",
  atlassian: "Atlassian",
  box: "Box",
  calendly: "Calendly",
  cashapp: "Cash App",
  chase: "Chase",
  claude: "Claude",
  cloudflare: "Cloudflare",
  coinbase: "Coinbase",
  databricks: "Databricks",
  datadog: "Datadog",
  discord: "Discord",
  docker: "Docker",
  doordash: "DoorDash",
  dropbox: "Dropbox",
  ebay: "eBay",
  etsy: "Etsy",
  evernote: "Evernote",
  facebook: "Facebook",
  fedex: "FedEx",
  figma: "Figma",
  framer: "Framer",
  github: "GitHub",
  gmail: "Gmail",
  google: "Google",
  googlecalendar: "Google Calendar",
  googledocs: "Google Docs",
  googledrive: "Google Drive",
  googlemeet: "Google Meet",
  googlesheets: "Google Sheets",
  graphql: "GraphQL",
  gusto: "Gusto",
  hubspot: "HubSpot",
  imessage: "iMessage",
  instagram: "Instagram",
  intercom: "Intercom",
  javascript: "JavaScript",
  jira: "Jira",
  klarna: "Klarna",
  kubernetes: "Kubernetes",
  linear: "Linear",
  loom: "Loom",
  mailchimp: "MailChimp",
  mastercard: "MasterCard",
  medium: "Medium",
  messenger: "Messenger",
  meta: "Meta",
  mongodb: "MongoDB",
  mysql: "MySQL",
  netflix: "Netflix",
  nextdotjs: "Next.js",
  nodedotjs: "Node.js",
  notion: "Notion",
  obsidian: "Obsidian",
  paypal: "PayPal",
  perplexity: "Perplexity",
  pinterest: "Pinterest",
  postgresql: "PostgreSQL",
  proton: "Proton",
  protonmail: "Proton Mail",
  python: "Python",
  quickbooks: "QuickBooks",
  react: "React",
  reddit: "Reddit",
  redis: "Redis",
  revolut: "Revolut",
  robinhood: "Robinhood",
  sap: "SAP",
  sentry: "Sentry",
  shopify: "Shopify",
  signal: "Signal",
  sketch: "Sketch",
  snapchat: "Snapchat",
  snowflake: "Snowflake",
  spotify: "Spotify",
  square: "Square",
  squarespace: "Squarespace",
  stripe: "Stripe",
  sqlite: "SQLite",
  substack: "Substack",
  supabase: "Supabase",
  target: "Target",
  telegram: "Telegram",
  tiktok: "TikTok",
  todoist: "Todoist",
  trello: "Trello",
  twitch: "Twitch",
  typescript: "TypeScript",
  uber: "Uber",
  ups: "UPS",
  usps: "USPS",
  venmo: "Venmo",
  vercel: "Vercel",
  visa: "Visa",
  webex: "Webex",
  webflow: "Webflow",
  whatsapp: "WhatsApp",
  wise: "Wise",
  wix: "Wix",
  wordpress: "WordPress",
  x: "X",
  xero: "Xero",
  youtube: "YouTube",
  zapier: "Zapier",
  zelle: "Zelle",
  zendesk: "Zendesk",
  zoom: "Zoom",
} as const satisfies Record<string, string>;

/** Typed autocomplete for BrandIcon's slug prop. */
export type BrandSlug = keyof typeof brands;
