// PLACEHOLDER — populated at scaffold time from the toolkit's packages/mac-chrome
// (copy that package over this directory; see the toolkit's references/workflows.md).
// The stub implements exactly the surface the template pages use, with the real
// package's prop shapes, so vendoring is a drop-in replacement.
export {
  ChatWindow,
  ChooserWindow,
  createStoredIdList,
  DesktopShell,
  defaultDockItems,
  finderKeyTarget,
  FinderWindow,
  MacDetailsMenu,
  MacDock,
  MacMenu,
  MacToolbar,
  MenuBarExtra,
  QuickLook,
  SetupAssistant,
  SetupHeading,
  Sheet,
  SystemSymbol,
  ToolbarButton,
  ToolbarCapsule,
  ToolbarGlyph,
  ToolbarSearchBubble,
  ToolbarToggle,
  TrafficLights,
  useModalFocusTrap,
  useWindowDrag,
  WindowChrome,
} from "./stub.tsx";
export type {
  ChatAuthor,
  ChatComposer,
  ChatMessage,
  ChatRole,
  ChatSearch,
  ChooserChoice,
  ChooserCommand,
  ChooserCommandSection,
  ChooserSecondaryGroup,
  Conversation,
  DesktopShellProps,
  DockItem,
  FinderEntry,
  FinderSearch,
  FinderSelection,
  FinderViewMode,
  MenuAction,
  MenuBarMenu,
  MenuCommand,
  MenuEntry,
  MenuPopoverConfig,
  MenuSpec,
  SidebarItem,
  SidebarSection,
  SetupStep,
  StoredIdList,
  SystemSymbolName,
  ToolbarGlyphName,
  WindowFrame,
} from "./stub.tsx";
